Iter5
golikoffegor/go-url-shortening-service pull request #7
Opened 2024-03-12 18:54 UTC by golikoffegor

2024-03-13 20:17 UTC, rktkov requested changes

2024-03-13 20:17 UTC, rktkov commented on internal/storage/storage.go
> +type MetricsStorage interface {
Определение интерфейса стоит перенести в пакет, где он используется.

2024-03-13 20:17 UTC, rktkov commented on internal/storage/storage.go
> +func (m *MemStorage) UpdateURLAddress(key string, url string) {
Сигнатура функции не соответствует сигнатуре в интерфейсе. Т.е. структура МемХранилище не реализует интерфейс.

2024-03-13 20:17 UTC, rktkov commented on internal/storage/storage.go
> +func (m *MemStorage) GetURLAddress(key string) string {
Тут лучше добавить еще один возвращаемый аргумент типа bool, который бы нам говорил, а существует ли ключ в мапе. Потому что если ключа не существует, мапа вернет пустую строку.

2024-03-13 20:17 UTC, rktkov commented on internal/storage/storage.go
> +var Storage *MemStorage
Лучше эту переменную сделать полем в структуре в пакете handler

2024-03-16 09:20 UTC, golikoffegor commented on internal/storage/storage.go
> +var Storage *MemStorage
Поправил

2024-03-16 09:20 UTC, golikoffegor commented on internal/storage/storage.go
> +func (m *MemStorage) GetURLAddress(key string) string {
Поправил

2024-03-16 09:20 UTC, golikoffegor commented on internal/storage/storage.go
> +func (m *MemStorage) UpdateURLAddress(key string, url string) {
Поправил

2024-03-16 09:20 UTC, golikoffegor commented on internal/storage/storage.go
> +type MetricsStorage interface {
Поправил

2024-03-19 11:44 UTC, rktkov approved these changes

2024-03-19 13:04 UTC, merged